#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model SHAF25_forLuigi.Examples.SHAF25_component_scalable_linear
 Dymola Version 2022x (64-bit), 2021-10-08 translated this at Wed Mar  1 13:34:33 2023

   */

#include <matrixop.h>
#include "matrixop.c"
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    10
#define NX2_   0
#define NU_    1
#define NY_    5
#define NW_    70
#define NP_    20
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -293223889
#define NHash2_ 115723745
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    64
#define SizePre_ 1
#define SizeEq_ 5
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="SHAF25_forLuigi.Examples.SHAF25_component_scalable_linear";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/egseg/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[19]={6 , 4 , 1 , 2 , 3 , 9 , 2 , 4 , 10 , 1 , 5
   , 1 , 6 , 1 , 7 , 1 , 8 , 0 , 0};
static int QJacobianGrp0[11]={2, 3, 0, 3, 0, 3, 0, 9, 0, 9, 0};
static int QJacobianGrp1[11]={0, 4, 4, 4, 0, 4, 0, 10, 10, 10, 0};
static int QJacobianGrp2[7]={1, 5 , 3 , 4 , 6 , 8 , 0};
static int QJacobianGrp3[8]={1, 6 , 4 , 4 , 5 , 6 , 8 , 0};
static int QJacobianGrp4[7]={1, 7 , 3 , 6 , 8 , 10 , 0};
static int QJacobianGrp5[8]={1, 8 , 4 , 6 , 7 , 8 , 10 , 0};
DYMOLA_STATIC struct QJacobianTag_ QJacobianGC2_[7]={
{0, QJacobianGrp0},{0, QJacobianGrp1},{1, QJacobianGrp2},{1, QJacobianGrp3},{1, 
  QJacobianGrp4},{1, QJacobianGrp5},{0,0}};
DYMOLA_STATIC double QJacobianCD_[11]={0  , 44 , 55 , 66 , 70 , 72 , 72 , 70 , 66
   , 132 , 130};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct)
DYNX(W_,2) = 5;
DYNX(W_,14) = 3;
DYNX(W_,17) = 3;
DYNX(W_,22) = 3;
DYNX(W_,27) = 3;
DYNX(W_,32) = 3;
DYNX(W_,37) = 0.0001;
DYNX(W_,38) = 4;
DYNX(W_,39) = false;
DYNX(W_,45) = 0.0001;
DYNX(W_,46) = 4;
DYNX(W_,47) = false;
DYNX(W_,53) = 0.0001;
DYNX(W_,54) = 4;
DYNX(W_,55) = false;
DYNX(W_,61) = 0.0001;
DYNX(W_,62) = 4;
DYNX(W_,63) = false;
DYNX(W_,67) = false;
DYNX(W_,68) = 0;
DYNX(W_,69) = 0.0;
DYNX(W_,0) = 0.0;
DYNX(W_,30) = 0.0;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(W_,1) = 6.283185307179586*DYNX(DP_,1);
DYNX(W_,3) = divGuarded(DYNX(DP_,3)*DYNX(DP_,0),"shaft.H[1]*SysData.S_b",sqr(
  DYNX(W_,1)),"shaft.wo^2");
DYNX(W_,4) = divGuarded(DYNX(DP_,4)*DYNX(DP_,0),"shaft.H[2]*SysData.S_b",sqr(
  DYNX(W_,1)),"shaft.wo^2");
DYNX(W_,5) = divGuarded(DYNX(DP_,5)*DYNX(DP_,0),"shaft.H[3]*SysData.S_b",sqr(
  DYNX(W_,1)),"shaft.wo^2");
DYNX(W_,6) = divGuarded(DYNX(DP_,6)*DYNX(DP_,0),"shaft.H[4]*SysData.S_b",sqr(
  DYNX(W_,1)),"shaft.wo^2");
DYNX(W_,7) = divGuarded(DYNX(DP_,7)*DYNX(DP_,0),"shaft.H[5]*SysData.S_b",sqr(
  DYNX(W_,1)),"shaft.wo^2");
DYNX(W_,8) = divGuarded(DYNX(DP_,0)*DYNX(DP_,8)*sqr(DYNX(DP_,2)),
  "SysData.S_b*(shaft.K[1]*shaft.p^2)",4*DYNX(W_,1),"4*shaft.wo");
DYNX(W_,9) = divGuarded(DYNX(DP_,0)*DYNX(DP_,9)*sqr(DYNX(DP_,2)),
  "SysData.S_b*(shaft.K[2]*shaft.p^2)",4*DYNX(W_,1),"4*shaft.wo");
DYNX(W_,10) = divGuarded(DYNX(DP_,0)*DYNX(DP_,10)*sqr(DYNX(DP_,2)),
  "SysData.S_b*(shaft.K[3]*shaft.p^2)",4*DYNX(W_,1),"4*shaft.wo");
DYNX(W_,11) = divGuarded(DYNX(DP_,0)*DYNX(DP_,11)*sqr(DYNX(DP_,2)),
  "SysData.S_b*(shaft.K[4]*shaft.p^2)",4*DYNX(W_,1),"4*shaft.wo");
DYNX(W_,13) = DYNX(W_,3);
DYNX(W_,16) = DYNX(W_,4);
DYNX(W_,21) = DYNX(W_,5);
DYNX(W_,26) = DYNX(W_,6);
DYNX(W_,31) = DYNX(W_,7);
DYNX(W_,35) = DYNX(W_,8);
DYNX(W_,36) = DYNX(DP_,12);
DYNX(W_,43) = DYNX(W_,9);
DYNX(W_,44) = DYNX(DP_,13);
DYNX(W_,51) = DYNX(W_,10);
DYNX(W_,52) = DYNX(DP_,14);
DYNX(W_,59) = DYNX(W_,11);
DYNX(W_,60) = DYNX(DP_,15);
InitialSection
#if defined(DynSimStruct)
DYNX(F_,3) = 0;
DYNX(F_,5) = 0;
DYNX(F_,7) = 0;
DYNX(F_,9) = 0;
#endif
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection
DYNX(Y_,0) = DYNX(X_,1);
DYNX(Y_,1) = DYNX(X_,3)+DYNX(X_,1);
DYNX(Y_,2) = DYNX(X_,5)+DYNX(Y_,1);
DYNX(Y_,3) = DYNX(X_,7)+DYNX(Y_,2);
DYNX(Y_,4) = DYNX(X_,9)+DYNX(Y_,3);

DynamicsSection
DYNX(W_,41) = DYNX(W_,35)*(DYNX(X_,2)-DYNX(DP_,16));
DYNX(W_,42) = DYNX(W_,36)*DYNX(X_,3);
DYNX(W_,12) = DYNX(W_,41)+DYNX(W_,42);
 /* Linear system of equations to solve. */
DYNX(F_,1) = RememberSimple_(DYNX(F_,1), 0);
SolveScalarLinearParametric(DYNX(W_,13),"shaft.inertia[1].J", DYNX(U_,0)+
  DYNX(W_,12),"small_torque+shaft.inertia[1].flange_b.tau", DYNX(F_,1),
  "der(shaft.inertia[1].w)");
 /* End of Equation Block */ 

DYNX(F_,0) = DYNX(X_,1);
DYNX(W_,57) = DYNX(W_,51)*(DYNX(X_,6)-DYNX(DP_,18));
DYNX(W_,58) = DYNX(W_,52)*DYNX(X_,7);
DYNX(W_,20) = DYNX(W_,57)+DYNX(W_,58);
DYNX(W_,49) = DYNX(W_,43)*(DYNX(X_,4)-DYNX(DP_,17));
DYNX(W_,50) = DYNX(W_,44)*DYNX(X_,5);
DYNX(W_,15) = DYNX(W_,49)+DYNX(W_,50);
 /* Linear system of equations to solve. */
DYNX(W_,24) = RememberSimple_(DYNX(W_,24), 1);
SolveScalarLinearParametric(DYNX(W_,21),"shaft.inertia[3].J", DYNX(W_,20)-
  DYNX(W_,15),"shaft.inertia[3].flange_b.tau-shaft.inertia[2].flange_b.tau", 
  DYNX(W_,24),"der(shaft.inertia[3].w)");
 /* End of Equation Block */ 

 /* Linear system of equations to solve. */
DYNX(W_,19) = RememberSimple_(DYNX(W_,19), 2);
SolveScalarLinearParametric(DYNX(W_,16),"shaft.inertia[2].J", DYNX(W_,15)-
  DYNX(W_,12),"shaft.inertia[2].flange_b.tau-shaft.inertia[1].flange_b.tau", 
  DYNX(W_,19),"der(shaft.inertia[2].w)");
 /* End of Equation Block */ 

DYNX(F_,5) = DYNX(W_,24)-DYNX(W_,19);
DYNX(W_,65) = DYNX(W_,59)*(DYNX(X_,8)-DYNX(DP_,19));
DYNX(W_,66) = DYNX(W_,60)*DYNX(X_,9);
DYNX(W_,25) = DYNX(W_,65)+DYNX(W_,66);
 /* Linear system of equations to solve. */
DYNX(W_,29) = RememberSimple_(DYNX(W_,29), 3);
SolveScalarLinearParametric(DYNX(W_,26),"shaft.inertia[4].J", DYNX(W_,25)-
  DYNX(W_,20),"shaft.inertia[4].flange_b.tau-shaft.inertia[3].flange_b.tau", 
  DYNX(W_,29),"der(shaft.inertia[4].w)");
 /* End of Equation Block */ 

DYNX(F_,7) = DYNX(W_,29)-DYNX(W_,24);
 /* Linear system of equations to solve. */
DYNX(W_,34) = RememberSimple_(DYNX(W_,34), 4);
SolveScalarLinearParametric(DYNX(W_,31),"shaft.inertia[5].J",  -DYNX(W_,25),
  " -shaft.inertia[4].flange_b.tau", DYNX(W_,34),"der(shaft.inertia[5].w)");
 /* End of Equation Block */ 

DYNX(F_,9) = DYNX(W_,34)-DYNX(W_,29);
DYNX(F_,8) = DYNX(X_,9);
DYNX(F_,6) = DYNX(X_,7);
DYNX(F_,4) = DYNX(X_,5);
DYNX(F_,2) = DYNX(X_,3);
DYNX(F_,3) = DYNX(W_,19)-DYNX(F_,1);

AcceptedSection1

AcceptedSection2
DYNX(W_,18) = DYNX(X_,2)+DYNX(X_,0);
DYNX(W_,23) = DYNX(X_,4)+DYNX(W_,18);
DYNX(W_,28) = DYNX(X_,6)+DYNX(W_,23);
DYNX(W_,33) = DYNX(X_,8)+DYNX(W_,28);
DYNX(W_,40) = DYNX(W_,42)*DYNX(X_,3);
DYNX(W_,48) = DYNX(W_,50)*DYNX(X_,5);
DYNX(W_,56) = DYNX(W_,58)*DYNX(X_,7);
DYNX(W_,64) = DYNX(W_,66)*DYNX(X_,9);

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("SysData.S_b", "System base [V.A|MVA]", 0, 960000000, 0.0,0.0,\
100000000.0,0,560)
DeclareParameter("SysData.fn", "System frequency [Hz]", 1, 30, 0.0,0.0,0.0,0,560)
DeclareAlias2("shaft.flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[1].phi", 1, 1, 0, 4)
DeclareAlias2("shaft.flange_a.tau", "Cut torque in the flange [N.m]", \
"small_torque", 1, 2, 0, 132)
DeclareAlias2("shaft.flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[5].phi", 1, 5, 33, 4)
DeclareVariable("shaft.flange_b.tau", "Cut torque in the flange [N.m]", 0, 0.0, \
0.0,0.0,0.0,0,777)
DeclareVariable("shaft.wo", "rated angular frequency", 1, 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("shaft.p", "number of poles", 2, 2, 0.0,0.0,0.0,0,560)
DeclareVariable("shaft.N", "Number of masses [:#(type=Integer)]", 2, 5, 0.0,0.0,\
0.0,0,517)
DeclareParameter("shaft.H[1]", "Vector of moment of inertia values in p.u. [kg.m2]",\
 3, 0.176, 0.0,0.0,0.0,0,560)
DeclareParameter("shaft.H[2]", "Vector of moment of inertia values in p.u. [kg.m2]",\
 4, 1.427, 0.0,0.0,0.0,0,560)
DeclareParameter("shaft.H[3]", "Vector of moment of inertia values in p.u. [kg.m2]",\
 5, 1.428, 0.0,0.0,0.0,0,560)
DeclareParameter("shaft.H[4]", "Vector of moment of inertia values in p.u. [kg.m2]",\
 6, 1.428, 0.0,0.0,0.0,0,560)
DeclareParameter("shaft.H[5]", "Vector of moment of inertia values in p.u. [kg.m2]",\
 7, 0.869, 0.0,0.0,0.0,0,560)
DeclareVariable("shaft.J[1]", "[kg.m2]", 3, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("shaft.J[2]", "[kg.m2]", 4, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("shaft.J[3]", "[kg.m2]", 5, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("shaft.J[4]", "[kg.m2]", 6, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("shaft.J[5]", "[kg.m2]", 7, 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("shaft.K[1]", "p.u. torque/rad [N.m/rad]", 8, 17.78, 0.0,0.0,\
0.0,0,560)
DeclareParameter("shaft.K[2]", "p.u. torque/rad [N.m/rad]", 9, 27.66, 0.0,0.0,\
0.0,0,560)
DeclareParameter("shaft.K[3]", "p.u. torque/rad [N.m/rad]", 10, 31.31, 0.0,0.0,\
0.0,0,560)
DeclareParameter("shaft.K[4]", "p.u. torque/rad [N.m/rad]", 11, 37.25, 0.0,0.0,\
0.0,0,560)
DeclareVariable("shaft.c[1]", "[N.m/rad]", 8, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("shaft.c[2]", "[N.m/rad]", 9, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("shaft.c[3]", "[N.m/rad]", 10, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("shaft.c[4]", "[N.m/rad]", 11, 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("shaft.d[1]", "Vector of damping constant values in Nms/rad [N.m.s/rad]",\
 12, 1E-60, 0.0,0.0,0.0,0,560)
DeclareParameter("shaft.d[2]", "Vector of damping constant values in Nms/rad [N.m.s/rad]",\
 13, 1E-60, 0.0,0.0,0.0,0,560)
DeclareParameter("shaft.d[3]", "Vector of damping constant values in Nms/rad [N.m.s/rad]",\
 14, 1E-60, 0.0,0.0,0.0,0,560)
DeclareParameter("shaft.d[4]", "Vector of damping constant values in Nms/rad [N.m.s/rad]",\
 15, 1E-60, 0.0,0.0,0.0,0,560)
DeclareAlias2("shaft.inertia[1].flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[1].phi", 1, 1, 0, 4)
DeclareAlias2("shaft.inertia[1].flange_a.tau", "Cut torque in the flange [N.m]",\
 "small_torque", 1, 2, 0, 132)
DeclareAlias2("shaft.inertia[1].flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[1].phi", 1, 1, 0, 4)
DeclareVariable("shaft.inertia[1].flange_b.tau", "Cut torque in the flange [N.m]",\
 12, 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("shaft.inertia[1].J", "Moment of inertia [kg.m2]", 13, 1, 0.0,\
1E+100,0.0,0,513)
DeclareVariable("shaft.inertia[1].stateSelect", "Priority to use phi and w as states [:#(type=StateSelect)]",\
 14, 3, 1.0,5.0,0.0,0,1541)
DeclareState("shaft.inertia[1].phi", "Absolute rotation angle of component [rad|deg]",\
 0, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("shaft.inertia[1].der(phi)", "der(Absolute rotation angle of component) [rad/s]",\
 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("shaft.inertia[1].w", "Absolute angular velocity of component (= der(phi)) [rad/s]",\
 1, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("shaft.inertia[1].der(w)", "der(Absolute angular velocity of component (= der(phi))) [rad/s2]",\
 1, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("shaft.inertia[1].a", "Absolute angular acceleration of component (= der(w)) [rad/s2]",\
 "shaft.inertia[1].der(w)", 1, 6, 1, 0)
DeclareAlias2("shaft.inertia[2].flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[2].phi", 1, 5, 18, 4)
DeclareAlias2("shaft.inertia[2].flange_a.tau", "Cut torque in the flange [N.m]",\
 "shaft.inertia[1].flange_b.tau", -1, 5, 12, 132)
DeclareAlias2("shaft.inertia[2].flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[2].phi", 1, 5, 18, 4)
DeclareVariable("shaft.inertia[2].flange_b.tau", "Cut torque in the flange [N.m]",\
 15, 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("shaft.inertia[2].J", "Moment of inertia [kg.m2]", 16, 1, 0.0,\
1E+100,0.0,0,513)
DeclareVariable("shaft.inertia[2].stateSelect", "Priority to use phi and w as states [:#(type=StateSelect)]",\
 17, 3, 1.0,5.0,0.0,0,1541)
DeclareVariable("shaft.inertia[2].phi", "Absolute rotation angle of component [rad|deg]",\
 18, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("shaft.inertia[2].der(phi)", "der(Absolute rotation angle of component) [rad/s]",\
 "small_speed[2]", 1, 3, 1, 0)
DeclareAlias2("shaft.inertia[2].w", "Absolute angular velocity of component (= der(phi)) [rad/s]",\
 "small_speed[2]", 1, 3, 1, 0)
DeclareVariable("shaft.inertia[2].der(w)", "der(Absolute angular velocity of component (= der(phi))) [rad/s2]",\
 19, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("shaft.inertia[2].a", "Absolute angular acceleration of component (= der(w)) [rad/s2]",\
 "shaft.inertia[2].der(w)", 1, 5, 19, 0)
DeclareAlias2("shaft.inertia[3].flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[3].phi", 1, 5, 23, 4)
DeclareAlias2("shaft.inertia[3].flange_a.tau", "Cut torque in the flange [N.m]",\
 "shaft.inertia[2].flange_b.tau", -1, 5, 15, 132)
DeclareAlias2("shaft.inertia[3].flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[3].phi", 1, 5, 23, 4)
DeclareVariable("shaft.inertia[3].flange_b.tau", "Cut torque in the flange [N.m]",\
 20, 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("shaft.inertia[3].J", "Moment of inertia [kg.m2]", 21, 1, 0.0,\
1E+100,0.0,0,513)
DeclareVariable("shaft.inertia[3].stateSelect", "Priority to use phi and w as states [:#(type=StateSelect)]",\
 22, 3, 1.0,5.0,0.0,0,1541)
DeclareVariable("shaft.inertia[3].phi", "Absolute rotation angle of component [rad|deg]",\
 23, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("shaft.inertia[3].der(phi)", "der(Absolute rotation angle of component) [rad/s]",\
 "small_speed[3]", 1, 3, 2, 0)
DeclareAlias2("shaft.inertia[3].w", "Absolute angular velocity of component (= der(phi)) [rad/s]",\
 "small_speed[3]", 1, 3, 2, 0)
DeclareVariable("shaft.inertia[3].der(w)", "der(Absolute angular velocity of component (= der(phi))) [rad/s2]",\
 24, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("shaft.inertia[3].a", "Absolute angular acceleration of component (= der(w)) [rad/s2]",\
 "shaft.inertia[3].der(w)", 1, 5, 24, 0)
DeclareAlias2("shaft.inertia[4].flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[4].phi", 1, 5, 28, 4)
DeclareAlias2("shaft.inertia[4].flange_a.tau", "Cut torque in the flange [N.m]",\
 "shaft.inertia[3].flange_b.tau", -1, 5, 20, 132)
DeclareAlias2("shaft.inertia[4].flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[4].phi", 1, 5, 28, 4)
DeclareVariable("shaft.inertia[4].flange_b.tau", "Cut torque in the flange [N.m]",\
 25, 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("shaft.inertia[4].J", "Moment of inertia [kg.m2]", 26, 1, 0.0,\
1E+100,0.0,0,513)
DeclareVariable("shaft.inertia[4].stateSelect", "Priority to use phi and w as states [:#(type=StateSelect)]",\
 27, 3, 1.0,5.0,0.0,0,1541)
DeclareVariable("shaft.inertia[4].phi", "Absolute rotation angle of component [rad|deg]",\
 28, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("shaft.inertia[4].der(phi)", "der(Absolute rotation angle of component) [rad/s]",\
 "small_speed[4]", 1, 3, 3, 0)
DeclareAlias2("shaft.inertia[4].w", "Absolute angular velocity of component (= der(phi)) [rad/s]",\
 "small_speed[4]", 1, 3, 3, 0)
DeclareVariable("shaft.inertia[4].der(w)", "der(Absolute angular velocity of component (= der(phi))) [rad/s2]",\
 29, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("shaft.inertia[4].a", "Absolute angular acceleration of component (= der(w)) [rad/s2]",\
 "shaft.inertia[4].der(w)", 1, 5, 29, 0)
DeclareAlias2("shaft.inertia[5].flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[5].phi", 1, 5, 33, 4)
DeclareAlias2("shaft.inertia[5].flange_a.tau", "Cut torque in the flange [N.m]",\
 "shaft.inertia[4].flange_b.tau", -1, 5, 25, 132)
DeclareAlias2("shaft.inertia[5].flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[5].phi", 1, 5, 33, 4)
DeclareVariable("shaft.inertia[5].flange_b.tau", "Cut torque in the flange [N.m]",\
 30, 0.0, 0.0,0.0,0.0,0,777)
DeclareVariable("shaft.inertia[5].J", "Moment of inertia [kg.m2]", 31, 1, 0.0,\
1E+100,0.0,0,513)
DeclareVariable("shaft.inertia[5].stateSelect", "Priority to use phi and w as states [:#(type=StateSelect)]",\
 32, 3, 1.0,5.0,0.0,0,1541)
DeclareVariable("shaft.inertia[5].phi", "Absolute rotation angle of component [rad|deg]",\
 33, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("shaft.inertia[5].der(phi)", "der(Absolute rotation angle of component) [rad/s]",\
 "small_speed[5]", 1, 3, 4, 0)
DeclareAlias2("shaft.inertia[5].w", "Absolute angular velocity of component (= der(phi)) [rad/s]",\
 "small_speed[5]", 1, 3, 4, 0)
DeclareVariable("shaft.inertia[5].der(w)", "der(Absolute angular velocity of component (= der(phi))) [rad/s2]",\
 34, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("shaft.inertia[5].a", "Absolute angular acceleration of component (= der(w)) [rad/s2]",\
 "shaft.inertia[5].der(w)", 1, 5, 34, 0)
DeclareVariable("shaft.springdamper[1].c", "Spring constant [N.m/rad]", 35, \
100000.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("shaft.springdamper[1].d", "Damping constant [N.m.s/rad]", 36, 0,\
 0.0,1E+100,0.0,0,513)
DeclareParameter("shaft.springdamper[1].phi_rel0", "Unstretched spring angle [rad|deg]",\
 16, 0, 0.0,0.0,0.0,0,560)
DeclareState("shaft.springdamper[1].phi_rel", "Relative rotation angle (= flange_b.phi - flange_a.phi) [rad|deg]",\
 2, 0, 0.0,0.0,0.0001,0,560)
DeclareDerivative("shaft.springdamper[1].der(phi_rel)", "der(Relative rotation angle (= flange_b.phi - flange_a.phi)) [rad/s]",\
 2, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("shaft.springdamper[1].w_rel", "Relative angular velocity (= der(phi_rel)) [rad/s]",\
 3, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("shaft.springdamper[1].der(w_rel)", "der(Relative angular velocity (= der(phi_rel))) [rad/s2]",\
 3, 0, 0.0,0.0,0.0,0,512)
DeclareAlias2("shaft.springdamper[1].a_rel", "Relative angular acceleration (= der(w_rel)) [rad/s2]",\
 "shaft.springdamper[1].der(w_rel)", 1, 6, 3, 0)
DeclareAlias2("shaft.springdamper[1].tau", "Torque between flanges (= flange_b.tau) [N.m]",\
 "shaft.inertia[1].flange_b.tau", 1, 5, 12, 0)
DeclareAlias2("shaft.springdamper[1].flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[1].phi", 1, 1, 0, 4)
DeclareAlias2("shaft.springdamper[1].flange_a.tau", "Cut torque in the flange [N.m]",\
 "shaft.inertia[1].flange_b.tau", -1, 5, 12, 132)
DeclareAlias2("shaft.springdamper[1].flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[2].phi", 1, 5, 18, 4)
DeclareAlias2("shaft.springdamper[1].flange_b.tau", "Cut torque in the flange [N.m]",\
 "shaft.inertia[1].flange_b.tau", 1, 5, 12, 132)
DeclareVariable("shaft.springdamper[1].phi_nominal", "Nominal value of phi_rel (used for scaling) [rad|rad]",\
 37, 0.0001, 0.0,1E+100,0.0,0,513)
DeclareVariable("shaft.springdamper[1].stateSelect", "Priority to use phi_rel and w_rel as states [:#(type=StateSelect)]",\
 38, 4, 1.0,5.0,0.0,0,1541)
DeclareVariable("shaft.springdamper[1].useHeatPort", "= true, if heatPort is enabled [:#(type=Boolean)]",\
 39, false, 0.0,0.0,0.0,0,1539)
DeclareVariable("shaft.springdamper[1].lossPower", "Loss power leaving component via heatPort (> 0, if heat is flowing out of component) [W]",\
 40, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("shaft.springdamper[1].tau_c", "Spring torque [N.m]", 41, 0.0, \
0.0,0.0,0.0,0,2560)
DeclareVariable("shaft.springdamper[1].tau_d", "Damping torque [N.m]", 42, 0.0, \
0.0,0.0,0.0,0,2560)
DeclareVariable("shaft.springdamper[2].c", "Spring constant [N.m/rad]", 43, \
100000.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("shaft.springdamper[2].d", "Damping constant [N.m.s/rad]", 44, 0,\
 0.0,1E+100,0.0,0,513)
DeclareParameter("shaft.springdamper[2].phi_rel0", "Unstretched spring angle [rad|deg]",\
 17, 0, 0.0,0.0,0.0,0,560)
DeclareState("shaft.springdamper[2].phi_rel", "Relative rotation angle (= flange_b.phi - flange_a.phi) [rad|deg]",\
 4, 0, 0.0,0.0,0.0001,0,560)
DeclareDerivative("shaft.springdamper[2].der(phi_rel)", "der(Relative rotation angle (= flange_b.phi - flange_a.phi)) [rad/s]",\
 4, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("shaft.springdamper[2].w_rel", "Relative angular velocity (= der(phi_rel)) [rad/s]",\
 5, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("shaft.springdamper[2].der(w_rel)", "der(Relative angular velocity (= der(phi_rel))) [rad/s2]",\
 5, 0, 0.0,0.0,0.0,0,512)
DeclareAlias2("shaft.springdamper[2].a_rel", "Relative angular acceleration (= der(w_rel)) [rad/s2]",\
 "shaft.springdamper[2].der(w_rel)", 1, 6, 5, 0)
DeclareAlias2("shaft.springdamper[2].tau", "Torque between flanges (= flange_b.tau) [N.m]",\
 "shaft.inertia[2].flange_b.tau", 1, 5, 15, 0)
DeclareAlias2("shaft.springdamper[2].flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[2].phi", 1, 5, 18, 4)
DeclareAlias2("shaft.springdamper[2].flange_a.tau", "Cut torque in the flange [N.m]",\
 "shaft.inertia[2].flange_b.tau", -1, 5, 15, 132)
DeclareAlias2("shaft.springdamper[2].flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[3].phi", 1, 5, 23, 4)
DeclareAlias2("shaft.springdamper[2].flange_b.tau", "Cut torque in the flange [N.m]",\
 "shaft.inertia[2].flange_b.tau", 1, 5, 15, 132)
DeclareVariable("shaft.springdamper[2].phi_nominal", "Nominal value of phi_rel (used for scaling) [rad|rad]",\
 45, 0.0001, 0.0,1E+100,0.0,0,513)
DeclareVariable("shaft.springdamper[2].stateSelect", "Priority to use phi_rel and w_rel as states [:#(type=StateSelect)]",\
 46, 4, 1.0,5.0,0.0,0,1541)
DeclareVariable("shaft.springdamper[2].useHeatPort", "= true, if heatPort is enabled [:#(type=Boolean)]",\
 47, false, 0.0,0.0,0.0,0,1539)
DeclareVariable("shaft.springdamper[2].lossPower", "Loss power leaving component via heatPort (> 0, if heat is flowing out of component) [W]",\
 48, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("shaft.springdamper[2].tau_c", "Spring torque [N.m]", 49, 0.0, \
0.0,0.0,0.0,0,2560)
DeclareVariable("shaft.springdamper[2].tau_d", "Damping torque [N.m]", 50, 0.0, \
0.0,0.0,0.0,0,2560)
DeclareVariable("shaft.springdamper[3].c", "Spring constant [N.m/rad]", 51, \
100000.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("shaft.springdamper[3].d", "Damping constant [N.m.s/rad]", 52, 0,\
 0.0,1E+100,0.0,0,513)
DeclareParameter("shaft.springdamper[3].phi_rel0", "Unstretched spring angle [rad|deg]",\
 18, 0, 0.0,0.0,0.0,0,560)
DeclareState("shaft.springdamper[3].phi_rel", "Relative rotation angle (= flange_b.phi - flange_a.phi) [rad|deg]",\
 6, 0, 0.0,0.0,0.0001,0,560)
DeclareDerivative("shaft.springdamper[3].der(phi_rel)", "der(Relative rotation angle (= flange_b.phi - flange_a.phi)) [rad/s]",\
 6, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("shaft.springdamper[3].w_rel", "Relative angular velocity (= der(phi_rel)) [rad/s]",\
 7, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("shaft.springdamper[3].der(w_rel)", "der(Relative angular velocity (= der(phi_rel))) [rad/s2]",\
 7, 0, 0.0,0.0,0.0,0,512)
DeclareAlias2("shaft.springdamper[3].a_rel", "Relative angular acceleration (= der(w_rel)) [rad/s2]",\
 "shaft.springdamper[3].der(w_rel)", 1, 6, 7, 0)
DeclareAlias2("shaft.springdamper[3].tau", "Torque between flanges (= flange_b.tau) [N.m]",\
 "shaft.inertia[3].flange_b.tau", 1, 5, 20, 0)
DeclareAlias2("shaft.springdamper[3].flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[3].phi", 1, 5, 23, 4)
DeclareAlias2("shaft.springdamper[3].flange_a.tau", "Cut torque in the flange [N.m]",\
 "shaft.inertia[3].flange_b.tau", -1, 5, 20, 132)
DeclareAlias2("shaft.springdamper[3].flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[4].phi", 1, 5, 28, 4)
DeclareAlias2("shaft.springdamper[3].flange_b.tau", "Cut torque in the flange [N.m]",\
 "shaft.inertia[3].flange_b.tau", 1, 5, 20, 132)
DeclareVariable("shaft.springdamper[3].phi_nominal", "Nominal value of phi_rel (used for scaling) [rad|rad]",\
 53, 0.0001, 0.0,1E+100,0.0,0,513)
DeclareVariable("shaft.springdamper[3].stateSelect", "Priority to use phi_rel and w_rel as states [:#(type=StateSelect)]",\
 54, 4, 1.0,5.0,0.0,0,1541)
DeclareVariable("shaft.springdamper[3].useHeatPort", "= true, if heatPort is enabled [:#(type=Boolean)]",\
 55, false, 0.0,0.0,0.0,0,1539)
DeclareVariable("shaft.springdamper[3].lossPower", "Loss power leaving component via heatPort (> 0, if heat is flowing out of component) [W]",\
 56, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("shaft.springdamper[3].tau_c", "Spring torque [N.m]", 57, 0.0, \
0.0,0.0,0.0,0,2560)
DeclareVariable("shaft.springdamper[3].tau_d", "Damping torque [N.m]", 58, 0.0, \
0.0,0.0,0.0,0,2560)
DeclareVariable("shaft.springdamper[4].c", "Spring constant [N.m/rad]", 59, \
100000.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("shaft.springdamper[4].d", "Damping constant [N.m.s/rad]", 60, 0,\
 0.0,1E+100,0.0,0,513)
DeclareParameter("shaft.springdamper[4].phi_rel0", "Unstretched spring angle [rad|deg]",\
 19, 0, 0.0,0.0,0.0,0,560)
DeclareState("shaft.springdamper[4].phi_rel", "Relative rotation angle (= flange_b.phi - flange_a.phi) [rad|deg]",\
 8, 0, 0.0,0.0,0.0001,0,560)
DeclareDerivative("shaft.springdamper[4].der(phi_rel)", "der(Relative rotation angle (= flange_b.phi - flange_a.phi)) [rad/s]",\
 8, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("shaft.springdamper[4].w_rel", "Relative angular velocity (= der(phi_rel)) [rad/s]",\
 9, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("shaft.springdamper[4].der(w_rel)", "der(Relative angular velocity (= der(phi_rel))) [rad/s2]",\
 9, 0, 0.0,0.0,0.0,0,512)
DeclareAlias2("shaft.springdamper[4].a_rel", "Relative angular acceleration (= der(w_rel)) [rad/s2]",\
 "shaft.springdamper[4].der(w_rel)", 1, 6, 9, 0)
DeclareAlias2("shaft.springdamper[4].tau", "Torque between flanges (= flange_b.tau) [N.m]",\
 "shaft.inertia[4].flange_b.tau", 1, 5, 25, 0)
DeclareAlias2("shaft.springdamper[4].flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[4].phi", 1, 5, 28, 4)
DeclareAlias2("shaft.springdamper[4].flange_a.tau", "Cut torque in the flange [N.m]",\
 "shaft.inertia[4].flange_b.tau", -1, 5, 25, 132)
DeclareAlias2("shaft.springdamper[4].flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[5].phi", 1, 5, 33, 4)
DeclareAlias2("shaft.springdamper[4].flange_b.tau", "Cut torque in the flange [N.m]",\
 "shaft.inertia[4].flange_b.tau", 1, 5, 25, 132)
DeclareVariable("shaft.springdamper[4].phi_nominal", "Nominal value of phi_rel (used for scaling) [rad|rad]",\
 61, 0.0001, 0.0,1E+100,0.0,0,513)
DeclareVariable("shaft.springdamper[4].stateSelect", "Priority to use phi_rel and w_rel as states [:#(type=StateSelect)]",\
 62, 4, 1.0,5.0,0.0,0,1541)
DeclareVariable("shaft.springdamper[4].useHeatPort", "= true, if heatPort is enabled [:#(type=Boolean)]",\
 63, false, 0.0,0.0,0.0,0,1539)
DeclareVariable("shaft.springdamper[4].lossPower", "Loss power leaving component via heatPort (> 0, if heat is flowing out of component) [W]",\
 64, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("shaft.springdamper[4].tau_c", "Spring torque [N.m]", 65, 0.0, \
0.0,0.0,0.0,0,2560)
DeclareVariable("shaft.springdamper[4].tau_d", "Damping torque [N.m]", 66, 0.0, \
0.0,0.0,0.0,0,2560)
DeclareInput("small_torque", "[N.m:#(prefix=input)]", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("torque1.useSupport", "= true, if support flange enabled, otherwise implicitly grounded [:#(type=Boolean)]",\
 67, false, 0.0,0.0,0.0,0,1539)
DeclareAlias2("torque1.flange.phi", "Absolute rotation angle of flange [rad|deg]",\
 "shaft.inertia[1].phi", 1, 1, 0, 4)
DeclareAlias2("torque1.flange.tau", "Cut torque in the flange [N.m]", \
"small_torque", -1, 2, 0, 132)
DeclareVariable("torque1.phi_support", "Absolute angle of support flange [rad|deg]",\
 68, 0, 0.0,0.0,0.0,0,2561)
DeclareAlias2("torque1.tau", "Accelerating torque acting at flange (= -flange.tau) [N.m]",\
 "small_torque", 1, 2, 0, 0)
DeclareAlias2("speedOut[1].y", "Value of Real output", "shaft.inertia[1].w", 1, 1,\
 1, 0)
DeclareAlias2("speedOut[2].y", "Value of Real output", "small_speed[2]", 1, 3, 1,\
 0)
DeclareAlias2("speedOut[3].y", "Value of Real output", "small_speed[3]", 1, 3, 2,\
 0)
DeclareAlias2("speedOut[4].y", "Value of Real output", "small_speed[4]", 1, 3, 3,\
 0)
DeclareAlias2("speedOut[5].y", "Value of Real output", "small_speed[5]", 1, 3, 4,\
 0)
DeclareOutput("small_speed[1]", "", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("small_speed[2]", "", 1, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("small_speed[3]", "", 2, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("small_speed[4]", "", 3, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("small_speed[5]", "", 4, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("flange_b1.phi", "Absolute rotation angle of flange [rad|deg]", \
"shaft.inertia[5].phi", 1, 5, 33, 4)
DeclareVariable("flange_b1.tau", "Cut torque in the flange [N.m]", 69, 0.0, \
0.0,0.0,0.0,0,777)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartPreBlock
preContI(DYNX(U_,0),"small_torque", 0.0, 0);
EndPreBlock
DYNPreInp(DYNX(U_,0),"small_torque", 0);
StartEqBlock
DoRemember_(DYNX(F_,1), 0.0, 0);
DoRemember_(DYNX(W_,19), 0.0, 2);
DoRemember_(DYNX(W_,24), 0.0, 1);
DoRemember_(DYNX(W_,29), 0.0, 3);
DoRemember_(DYNX(W_,34), 0.0, 4);
EndEqBlock
EndDataBlock
